language: c

compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
install:
  - echo  "Reached Install Section"
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
  - sudo apt-get install avrdude

script:
  - echo "Reached Script Section"
  - avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o buzzer.o ECS/buzzer.c
  - avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o distance.o ECS/distance.c
  - avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o main.o ECS/main.c
  - avr-gcc -mmcu=atmega328p buzzer.o distance.o main.o -o proj
  - avr-objcopy -O ihex -R .eeprom proj proj.hex
